global:
  scrape_interval: {{ prometheus.scrape_interval }}
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'web01'
    static_configs:
      - targets: ['192.168.56.105:9100']
    labels:
      group: 'web_servers'

  - job_name: 'web02'
    static_configs:
      - targets: ['192.168.56.106:9100']
    labels:
      group: 'web_servers'
